runtime: nodejs8 # For Node.js 8, use runtime: nodejs8

instance_class: F1

env_variables:
  BUCKET_NAME: "staging.power-scouter-225422.appspot.com"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto